### ISSUE TITLE
Automated testing

### ISSUE THREAD

**Issue by basil** [jenkinsci/packaging#225]
### What feature do you want to see added?

This repository lacks a `Jenkinsfile` or any CI/CD. This makes it all too easy for regressions to be introduced. As a result, this repository resists change. In order to move forward with critical modernization efforts such as `systemd(1)` support, a prerequisite task is adding test coverage to this repository. Once there is test coverage, we will be able to make major changes with confidence that we are not introducing regressions.

**Comment by basil** [comment]
Some "fat" images:

- [`dokken-images`](https://github.com/test-kitchen/dokken-images)

Some test orchestrators:

- [Test Kitchen](https://kitchen.ci/)
- [Molecule](https://molecule.readthedocs.io/)

Some test verifiers:

- [Chef InSpec](http://inspec.io/)
- [Serverspec](https://serverspec.org/)
- [Testinfra](https://testinfra.readthedocs.io/)
- [Goss](https://goss.rocks/)

**Comment by basil** [comment]
As of today automated testing has been added for:

- AlmaLinux 8
- CentOS Stream 8
- Debian 10
- Debian 11
- Fedora 34
- Fedora 35
- openSUSE Leap 15
- Oracle Linux 8
- Rocky Linux 8
- Ubuntu 18.04
- Ubuntu 20.04
- Ubuntu 21.04
- Ubuntu 21.10
- Ubuntu 22.04

**Comment by timja** [comment]
Any reason to keep this open?

**Comment by basil** [comment]
I think I'd like to see a little deeper coverage in test cases before declaring victory on this issue. The platform matrix is now reasonably broad, but the test coverage is still quite thin. While I don't think we need to implement all test cases that have been enumerated right away, I think we should add a few more in the short term than just a basic smoke test.

**Comment by basil** [comment]
Now that we do some basic testing that the Java process is running and that its PID matches the one in the PID file, I'm going to declare victory on this task.
