### ISSUE TITLE
Debian packaging puts the PID file in an odd place

### ISSUE THREAD

**Issue by basil** [jenkinsci/packaging#254]
### Jenkins and plugins versions report

<details>
  <summary>Environment</summary>

  
  ```text
  Paste the output here
  ```

</details>

### What Operating System are you using (both controller, and any agents involved in the problem)?

Ubuntu Jammy Jellyfish (development branch) x86_64

### Reproduction steps

Build the package with:

```bash
$ docker-compose run --rm packaging bash
$ ./prep.sh
$ make package
```

Then set up a virtual environment and run Molecule:

```bash
$ python3 -m venv venv
$ . venv/bin/activate
$ pip install -U pip wheel
$ pip install -r requirements.txt
$ molecule create && molecule converge
```

Log in to the Ubuntu VM and list PID files:

```bash
$ molecule login --host ubuntu-22-04
$ systemctl start jenkinstest.service
$ ls -la /var/run/**/*.pid
```

### Expected Results

The PID file should be in `/var/run`, like all the other Ubuntu PID files and the Jenkins PID file on RPM-based systems.

### Actual Results

The PID file is in `/var/run/jenkins`, which is inconsistent with other Ubuntu PID files and the Jenkins PID file on RPM-based systems.

### Anything else?

Fixing this needs to take into account the migration case where an existing installation has a PID file in the old location.

**Comment by jtnord** [comment]
historically (still the case?) because the pid file was written by Jenkins and as such you did not want to give Jenkins write access to /var/run  (at the same time all of the locations for things are incorrect and jenkins should not be in usr/share ... but /opt... ) (ref)[https://refspecs.linuxfoundation.org/fhs.shtml]
https://github.com/jenkinsci/packaging/blob/35e665912ef3dc3c735539667c485051428f49b1/deb/build/debian/jenkins.init#L99-L101

**Comment by basil** [comment]
I guess when we move to `systemd`, `systemd` will create the PID file and we won't need to worry about giving `jenkins` write access to `/var/run`.

**Comment by basil** [comment]
> I guess when we move to `systemd`, `systemd` will create the PID file and we won't need to worry about giving `jenkins` write access to `/var/run`.

Rather we would most likely use `Type=Simple` in the `systemd.service(5)` unit configuration, which [avoids  PID files altogether](https://www.freedesktop.org/software/systemd/man/systemd.service.html):

> Note that PID files should be avoided in modern projects. Use `Type=notify` or `Type=simple` where possible, which does not require use of PID files to determine the main process of a service and avoids needless forking.

**Comment by basil** [comment]
As of #266, we no longer use a PID file.
