### ISSUE TITLE
The systemd unit file does not define an optional EnvironmentFile

### ISSUE THREAD

**Issue by pingram3030** [jenkinsci/packaging#305]
### Jenkins and plugins versions report

rpm: jenkins-2.332.1-1.1.noarch

### What Operating System are you using (both controller, and any agents involved in the problem)?

CentOS 7

### Reproduction steps

The easiest example of this regression is:

1. Install Jenkins from http://pkg.jenkins.io/redhat-stable
2. Modify `JENKINS_ARGS` in `/etc/sysconfig/jenkins`
3. Restart jenkins
4. Run `ps auxfww` and note that jenkins does not have `JENKINS_ARGS` appended.

### Expected Results

Jenkins use the `EnvironmentFile` option in its systemd unit file [jenkins.service](https://github.com/jenkinsci/packaging/blob/master/systemd/jenkins.service) to optionally load `/etc/sysconfig/jenkins` (and all other vendor supported environment file locations).

### Actual Results

* After modifying `/etc/sysconfig/jenkins` none of the alterations I made are used.
    * Jenkins continues to start on port 8080 despite setting `JENKINS_PORT` in `/etc/sysconfig/jenkins`
    * Jenkins is not started with `JENKINS_ARGS`

### Anything else?

The default systemd unit should never be hand modified, so to temporarily get around this issue I created `/etc/systemd/system/jenkins.service.d/override.conf` with the content of:
```
[Service]
EnvironmentFile=-/etc/sysconfig/jenkins
```
I do not consider that creating an override file is a fix and am using it only a work around.

See `EnvironmentFile` under https://www.freedesktop.org/software/systemd/man/systemd.exec.html#Environment
> The argument passed should be an absolute filename or wildcard expression, optionally prefixed with "-", which indicates that if the file does not exist, it will not be read and no error or warning message is logged.

`EnvironmentFile` can be specified multiple times to ensure that all locations on all distributions can be used; i.e.
```
[Service]
EnvironmentFile=-/etc/sysconfig/jenkins
EnvironmentFile=-/etc/default/jenkins
```

I created this ticket as a bug because it's a regression from previous releases and modifying the environment file does nothing to modify Jenkins when it's started.

**Comment by basil** [comment]
The software is working as intended. Please refer to the following resources for information on this migration:

- [Linux installation packages migrated from System V `init` to `systemd`](https://www.jenkins.io/blog/2022/03/25/systemd-migration/)
- [Managing `systemd` services](https://www.jenkins.io/doc/book/system-administration/systemd-services/)
- [Managing the Jenkins systemd Service on CentOS 7.9](https://www.youtube.com/watch?v=MkokjTQ2ngc)
- [Managing the Jenkins systemd Service on Ubuntu 20.04](https://www.youtube.com/watch?v=pwR9TPW2oG4)
- [DigitalOcean `systemd` services and units tutorial](https://www.digitalocean.com/community/tutorials/how-to-use-systemctl-to-manage-systemd-services-and-units)
- [Understand and administering `systemd`](https://docs.fedoraproject.org/en-US/quick-docs/understanding-and-administering-systemd/)
