### ISSUE TITLE
create a static url to download the latest Jenkins.MSI file.

### ISSUE THREAD

**Issue by noyard** [jenkinsci/packaging#310]
### What feature do you want to see added?

I can download the latest Jenkins.war file with URL:
https://updates.jenkins.io/latest/jenkins.war

How can I download the latest Jenkins.msi file?

Please create a static url to download the latest Jenkins.MSI file.

**Comment by gounthar** [comment]
I thought https://www.jenkins.io/download/thank-you-downloading-windows-installer would work with redirection, but alas, it uses `Javascript` in the end so that

```bash
curl -L https://www.jenkins.io/download/thank-you-downloading-windows-installer --output jenkins.msi
```

doesn't work.

**Comment by lemeurherve** [comment]
From the webpage, this link is a direct download one:

<img width="337" alt="image" src="https://user-images.githubusercontent.com/91831478/172235960-4bd73a6b-bf43-40c2-8684-cb54797a91bb.png">

https://get.jenkins.io/windows/2.350/jenkins.msi

**Comment by gounthar** [comment]
You're perfectly right @lemeurherve , that's a direct link to the latest version of the msi. This week.
Each week, the link will change for the Windows version.
We have a link that redirects to the last version each week for the `.war`, maybe @noyard would like to get the very same kind of _generic_ link for the msi.

**Comment by noyard** [comment]
@gounthar Yes I would like to have a generic link for the MSI, just like you do for the [.WAR] file. 

Background...
I have a PowerShell script that checks a link to see if it has new content, if it does then it download the file and distributes it for users to update their Jenkins client.  I would like to offer the latest Jenkins MSI install.  I can parse a Html file but that can be problematic if the page changes drastically.

**Comment by lemeurherve** [comment]
As an easy workaround and since you're already scripting this download, you can retrieve latest Jenkins version with something like
```powershell
$releases = "https://api.github.com/repos/jenkinsci/jenkins/releases"
$tag = (Invoke-WebRequest $releases | ConvertFrom-Json)[0].tag_name
$lastJenkinsMsiURL = 'https://get.jenkins.io/windows/{0}/jenkins.msi' -f $tag
```

**Comment by noyard** [comment]
That works.  Much better than parsing a HTML.   Thanks.

**Comment by MarkEWaite** [comment]
@noyard I'm glad that you've found a solution.  That's great.

You may want to be careful with the assumptions that are implicit in the scripted download technique.  It uses the most recent release recorded on the Jenkins core repository on GitHub.  After a long term support release, that will be the most recent long term support release.  After a weekly release, that will be the most recent weekly release.

If you want only weekly releases, you may want to exclude tags that match the format `[1-9][.][1-9][0-9][0-9][.][0-9]`
